mysite/contact/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('contact.views',
    url(r'^formulario-contato/$', 'contact', name='contact'),
    url(r'^thanks/$', 'thanks', name='thanks'),
    url(r'^list/$', 'list', name='list')
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^contact/', include('contact.urls', namespace="con")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^servers/', include('cvteste.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

mysite/contact/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
# Classe
class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.question
	def was_published_recently(self):
		now = timezone.now()
		return (now - datetime.timedelta(days=1) <= self.pub_date <= now)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __unicode__(self):
		return self.choice_text

mysite/contact/forms.py
# -*- coding: utf-8 -*-

from django import forms

class ContactForm(forms.Form):
	name = forms.CharField(label = 'nome')
	email = forms.EmailField(label = 'e-mail')
	description = forms.CharField(label = u'descrição', widget = forms.Textarea)

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

mysite/polls/forms.py
class contactForm(forms.Form):
	subject=forms.CharField(max_length=100)
	message=forms.CharField()
	sender=forms.EmailField()
	cc_myself=forms.BooleanField

mysite/contact/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from contact.forms import ContactForm, DocumentForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from contact.models import Document
from random import randint
import json


def list(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile = request.FILES['docfile'])
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('con:list'))
    else:
        form = DocumentForm() # A empty, unbound form

    print request.revision
    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render_to_response(
        'contact/list.html',
        {'documents': documents, 'form': form,'REVISION':request.revision},
        context_instance=RequestContext(request),
    )




def contact2(request): 
    cntform = ContactForm()
    c = {}
    c['form'] = cntform
    c = RequestContext(request, c)

    template_name = 'contact/contact_form.html'
    return render_to_response(template_name, c)

def contact(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            print 'envia email'
            return HttpResponseRedirect('/bug/thanks')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()
    template_name = 'contact/contact_form.html'
    c = {}
    c['form'] = form
    c = RequestContext(request, c)

    return render_to_response(template_name, c)


def thanks(request):
    template_name = 'contact/thanks.html'
    d = {}
    return render_to_response(template_name, d)

def view(request):
    return request.revision

def chart(request):
    template_name = "contact/un.html"
    resultado = []
    count = 1
    for i in range(4):
        serie = []
        for i in range(5):
            serie.append(randint(0, 100))
        resultado.append(serie)
        serie = []
        count += 1
    c = {}
    c['res'] = json.dumps(resultado)
    c = RequestContext(request, c)

    return render_to_response(template_name, c)


def chart1(request):
    template_name = "contact/un1.html"
    resultado = []
    count = 1
    for i in range(4):
        serie = []
        for i in range(5):
            serie.append(randint(0, 100))
        resultado.append(serie)
        serie = []
        count += 1
    c = {}
    c['res'] = json.dumps(resultado)
    c = RequestContext(request, c)

    return render_to_response(template_name, c)


def chart2(request):
    template_name = "contact/un2.html"
    resultado = []
    count = 1
    for i in range(4):
        serie = []
        for i in range(5):
            serie.append(randint(0, 100))
        resultado.append(serie)
        serie = []
        count += 1
    c = {}
    c['res'] = json.dumps(resultado)
    c = RequestContext(request, c)

    return render_to_response(template_name, c)


def chart3(request):
    template_name = "contact/un3.html"
    resultado = []
    count = 1
    for i in range(4):
        serie = []
        for i in range(5):
            serie.append(randint(0, 100))
        resultado.append(serie)
        serie = []
        count += 1
    c = {}
    c['res'] = json.dumps(resultado)
    c = RequestContext(request, c)

    return render_to_response(template_name, c)

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django import forms

from polls.models import Choice, Poll


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.filter(
            pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any polls that aren't published yet.
        """
        return Poll.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):

    model = Poll
    template_name = 'polls/results.html'


def contact(request):
    if request.method == 'POST':
        form = Contact.Form(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['info@example.com']
            if cc_myself:
                recipients.append(sender)

            from django.core.mail import send_mail
            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/thanks!/')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {
        'form': form,
    })


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/polls/templates/polls/contact.html
<form action="/contact/" method="post">
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.subject.errors }}
        <label for="id_subject">Email subject:</label>
        {{ form.subject }}
    </div>
    <div class="fieldWrapper">
        {{ form.message.errors }}
        <label for="id_message">Your message:</label>
        {{ form.message }}
    </div>
    <div class="fieldWrapper">
        {{ form.sender.errors }}
        <label for="id_sender">Your email address:</label>
        {{ form.sender }}
    </div>
    <div class="fieldWrapper">
        {{ form.cc_myself.errors }}
        <label for="id_cc_myself">CC yourself?</label>
        {{ form.cc_myself }}
    </div>
    <p><input type="submit" value="Send message" /></p>
   


</form>

mysite/polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
<footer>
<link href="/detail.css?{{ REVISION }}" rel="stylesheet" type="text/css" media="screen" />
<script src="/detail.js?{{ REVISION }}"></script>
</footer>

mysite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<a href="{% url 'cvteste' %}"></a>
<footer>
</footer>

mysite/polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
<footer>
<link href="/results.css?{{ REVISION }}" rel="stylesheet" type="text/css" media="screen" />
<script src="/results.js?{{ REVISION }}"></script>
</footer>